const HOD_Details = {
  HOD: [
    {
      Name: "Dheeraj Rane",
      Title: "Faculty Coordinator",
    },
  ],
};

const Council_Member_Details = {
  Council: [
    {
      Name: "Nishant Gandhi",
      Title: "Chairman",
      linkedin: "https://www.linkedin.com/in/nishant-gandhi-1503",
      twitter: "https://www.twitter.com/nishant1503",
      github: "https://github.com/nishant1503",
      instagram: "https://www.instagram.com/_irresponsible__beardo_",
      facebook: "https://www.facebook.com/nishant.gandhi.1515",
    },
    {
      Name: "Sarthak Khandelwal",
      Title: "Vice Chairman",
      linkedin: "https://www.linkedin.com/in/forwet/",
      twitter: "https://twitter.com/Sarthak60130220",
      github: "https://github.com/sarthakforwet",
      instagram: "https://www.instagram.com/sarthakkhandelwal7676/",
      facebook: "https://www.facebook.com/sarthakforwet/",
    },
    {
      Name: "Hiteshi Gupta",
      Title: "Treasurer",
      linkedin: "https://www.linkedin.com/in/hiteshi-gupta-7a51b5191/",
      twitter: "https://www.twitter.com/hiteshii_",
      github: "",
      instagram: "https://www.instagram.com/hiteshiiiii__",
      facebook: "",
    },
  ],
};

const Core_Member_Details = {
  Core: [
    {
      Name: "Yash Sehgal",
      Title: "Junior Coordinator",
      linkedin: "https://www.linkedin.com/in/yash-sehgal-55b7711a4/",
      twitter: "https://twitter.com/YashSeh90869786",
      github: "https://www.github.com/yashsehgal",
      instagram: "https://www.instagram.com/sehgalyash_/",
      facebook: "https://www.facebook.com/yash.sehgal.96780/",
    },
    {
      Name: "Saud Hashmi",
      Title: "Head of Content",
      linkedin: "https://www.linkedin.com/in/saud-hashmi-19a317a3/",
      twitter: "https://twitter.com/Hash_Saud",
      github: "https://github.com/SuperbSaud/",
      instagram: "https://www.instagram.com/i_s.a.u.d/",
      facebook: "https://www.facebook.com/saud.hashmi.161/",
    },
    {
      Name: "Riya Ahuja",
      Title: "Head of Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/riyaahuja84",
      facebook: "",
    },
    {
      Name: "Samriddhi Kaur",
      Title: "Head of Graphics",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Ritika Maheshwari",
      Title: "Head of Marketing",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Mihir Dutta",
      Title: "Technical Head",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
  ],
};

const Executive_Member_Details = {
  Executive: [
    {
      Name: "Tanisha Jain",
      Title: "Graphic Designer",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Mayank Verma",
      Title: "Management Team",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Jaspreet Singh Saini",
      Title: "Graphic Designer",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Samarth Sharma",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Aditi Mandlik",
      Title: "Content and Graphics Team",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Preeti Mehta Jain",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Rajesh Nathani",
      Title: "Web Development Team",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Aditi Dandawate",
      Title: "Content and Graphics",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Suchismita Nanda",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Ishika Shahaney",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Raj Soni",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
    {
      Name: "Anushka Jain",
      Title: "Marketing and Management",
      linkedin: "",
      twitter: "",
      github: "",
      instagram: "",
      facebook: "",
    },
  ],
};

export default {
  HOD_Details,
  Council_Member_Details,
  Core_Member_Details,
  Executive_Member_Details,
};
