const HOD_Details = {
  HOD: [
    {
      Name: "Dheeraj Rane",
      Title: "Faculty Coordinator",
      type: 'faculty',
      email: 'dheeraj.rane@medicaps.ac.in'
    },
  ],
};

const Council_Member_Details = {
  Council: [
    {
      Name: "Nishant Gandhi",
      Title: "Chairman",
      linkedin: "https://www.linkedin.com/in/nishant-gandhi-1503",
      twitter: "https://www.twitter.com/nishant1503",
      github: "https://github.com/nishant1503",
      instagram: "https://www.instagram.com/_irresponsible__beardo_",
      facebook: "https://www.facebook.com/nishant.gandhi.1515",
    },
    {
      Name: "Sarthak Khandelwal",
      Title: "Vice Chairman",
      linkedin: "https://www.linkedin.com/in/forwet/",
      twitter: "https://twitter.com/Sarthak60130220",
      github: "https://github.com/sarthakforwet",
      instagram: "https://www.instagram.com/sarthakkhandelwal7676/",
      facebook: "https://www.facebook.com/sarthakforwet/",
    },
    {
      Name: "Hiteshi Gupta",
      Title: "Treasurer",
      linkedin: "https://www.linkedin.com/in/hiteshi-gupta-7a51b5191/",
      twitter: "https://www.twitter.com/hiteshii_",
      github: "",
      instagram: "https://www.instagram.com/hiteshiiiii__",
      facebook: "",
    },
  ],
};

const Core_Member_Details = {
  Core: [
    {
      Name: "Yash Sehgal",
      Title: "Junior Coordinator",
      linkedin: "https://www.linkedin.com/in/yash-sehgal-55b7711a4/",
      twitter: "https://twitter.com/YashSeh90869786",
      github: "https://www.github.com/yashsehgal",
      instagram: "https://www.instagram.com/sehgalyash_/",
      facebook: "https://www.facebook.com/yash.sehgal.96780/",
    },
    {
      Name: "Saud Hashmi",
      Title: "Head of Content",
      linkedin: "https://www.linkedin.com/in/saud-hashmi-19a317a3/",
      twitter: "https://twitter.com/Hash_Saud",
      github: "https://github.com/SuperbSaud/",
      instagram: "https://www.instagram.com/i_s.a.u.d/",
      facebook: "https://www.facebook.com/saud.hashmi.161/",
    },
    {
      Name: "Riya Ahuja",
      Title: "Head of Management",
      linkedin: "https://www.linkedin.com/in/riya-ahuja-81bb231b3/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/riyaahuja84",
      facebook: "",
    },
    {
      Name: "Samriddhi Kaur",
      Title: "Head of Graphics",
      linkedin: "https://www.linkedin.com/in/samriddhi-kaur-b02b78204/",
      twitter: "",
      github: "https://github.com/samriddhik562",
      instagram: "https://www.instagram.com/samriddhi.k.562/",
      facebook: "",
    },
    {
      Name: "Ritika Maheshwari",
      Title: "Head of Marketing",
      linkedin: "https://www.linkedin.com/in/ritika-maheshwari-7837871ab/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/__ritika16/",
      facebook: "",
    },
    {
      Name: "Mihir Dutta",
      Title: "Technical Head",
      linkedin: "https://www.linkedin.com/in/mihirduttaa/",
      twitter: "https://twitter.com/exclusivemihir",
      github: "https://github.com/mihirduttaa",
      instagram: "https://www.instagram.com/mihirduttaa/",
      facebook: "https://www.facebook.com/profile.php?id=100005641725979",
    },
  ],
};

const Executive_Member_Details = {
  Executive: [
    {
      Name: "Tanisha Jain",
      Title: "Graphic Designer",
      linkedin: "https://www.linkedin.com/in/tanisha-jain-60703120b/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/tanishahahaaha/",
      facebook: "",
    },
    {
      Name: "Mayank Verma",
      Title: "Management Team",
      linkedin: "https://www.linkedin.com/in/mayank-v-946404131/",
      twitter: "",
      github: "https://github.com/MVerma44",
      instagram: "https://www.instagram.com/vmayank_007/",
      facebook: "",
    },
    {
      Name: "Jaspreet Singh Saini",
      Title: "Graphic Designer",
      linkedin: "https://www.linkedin.com/in/jaspreet-singh-saini-a916111b2/",
      twitter: "https://twitter.com/s_jaspreet099",
      github: "https://github.com/Jaspreet099",
      instagram: "https://www.instagram.com/official_jaspreet_saini/",
      facebook: "",
    },
    {
      Name: "Samarth Sharma",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/samarth-sharma2406/",
      twitter: "",
      github: "https://github.com/24samarth",
      instagram: "https://www.instagram.com/_samarth_sharma._/",
      facebook: "",
    },
    {
      Name: "Aditi Mandlik",
      Title: "Content and Graphics Team",
      linkedin: "https://www.linkedin.com/in/aditi-mandlik-b95386209/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/aditimandlik/",
      facebook: "",
    },
    {
      Name: "Preeti Mehta Jain",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/prateeti-mehta-33186420a/",
      twitter: "https://twitter.com/PrateetiJ",
      github: "",
      instagram: "https://www.instagram.com/prateetimjain/",
      facebook: "",
    },
    {
      Name: "Rajesh Nathani",
      Title: "Web Development Team",
      linkedin: "https://www.linkedin.com/in/rajesh-nathani-5a186a145/",
      twitter: "",
      github: "https://github.com/RajeshNathani",
      instagram: "https://www.instagram.com/rajesh.nathani1/",
      facebook: "",
    },
    {
      Name: "Aditi Dandawate",
      Title: "Content and Graphics",
      linkedin: "https://www.linkedin.com/in/aditi-dandawate-84704120b",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/aditi_dandawate/",
      facebook: "",
    },
    {
      Name: "Suchismita Nanda",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/suchismita-nanda-221a4b201",
      twitter: "https://twitter.com/Suchi2407?s=08",
      github: "https://github.com/suchismita2407",
      instagram: "https://www.instagram.com/suchi_9624/",
      facebook: "",
    },
    {
      Name: "Ishika Shahaney",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/ishika-shahaney-b9b945201",
      twitter: "https://mobile.twitter.com/IShahaney",
      github: "https://github.com/Ishika1903",
      instagram: "https://www.instagram.com/__ishika1903/",
      facebook: "https://m.facebook.com/ishika.shahaney.5?ref=bookmarks",
    },
    {
      Name: "Raj Soni",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/raj-soni-5306141b6/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/raj_soni0717/",
      facebook: "",
    },
    {
      Name: "Anushka Jain",
      Title: "Marketing and Management",
      linkedin: "https://www.linkedin.com/in/anushka-jain-88a548209/",
      twitter: "",
      github: "",
      instagram: "https://www.instagram.com/anushkajain_28/",
      facebook: "",
    },
  ],
};

export default {
  HOD_Details,
  Council_Member_Details,
  Core_Member_Details,
  Executive_Member_Details,
};
